name: Build and Test
on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"

  pull_request:
    types: [opened, ready_for_review]

  workflow_call:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.x' ]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Generate go code
        run: go run -mod=mod entgo.io/ent/cmd/ent@v0.14.0 generate --feature sql/modifier --target ./pkg/db/ent ./pkg/db/schema
        working-directory: ./

      - name: Build
        run: go build -v .
        working-directory: ./cmd/alpamon

      - name: Run Tests
        run: go test -v ./...
