name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  goreleaser:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload AMD64 DEB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: alpamon_${{ github.ref_name }}_linux_amd64.deb
          path: dist/alpamon_${{ github.ref_name }}_linux_amd64.deb

      - name: Upload AMD64 RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: alpamon_${{ github.ref_name }}_linux_amd64.rpm
          path: dist/alpamon_${{ github.ref_name }}_linux_amd64.rpm

  packagecloud-deploy:
    needs: [goreleaser]
    runs-on: ubuntu-latest
    steps:
      - name: Download AMD64 DEB Artifacts
        uses: actions/download-artifact@v4
        with:
          name: alpamon_${{ github.ref_name }}_linux_amd64.deb

      - name: Download AMD64 RPM Artifacts
        uses: actions/download-artifact@v4
        with:
          name: alpamon_${{ github.ref_name }}_linux_amd64.rpm

      - run: ls

      - name: Upload AMD64 DEB to PackageCloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          package-name: alpamon_${{ github.ref_name }}_linux_amd64.deb
          packagecloud-username: alpacax
          packagecloud-repo: alpamon
          packagecloud-distrib: any/any
          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - name: Upload ARM64 DEB to PackageCloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          package-name: alpamon_${{ github.ref_name }}_linux_arm64.deb
          packagecloud-username: alpacax
          packagecloud-repo: alpamon
          packagecloud-distrib: any/any
          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - name: Upload AMD64 RPM to PackageCloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          package-name: alpamon_${{ github.ref_name }}_linux_amd64.rpm
          packagecloud-username: alpacax
          packagecloud-repo: alpamon
          packagecloud-distrib: rpm_any/rpm_any
          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - name: Upload ARM64 RPM to PackageCloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          package-name: alpamon_${{ github.ref_name }}_linux_arm64.rpm
          packagecloud-username: alpacax
          packagecloud-repo: alpamon
          packagecloud-distrib: rpm_any/rpm_any
          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}